console.log(" js string methods in     depth  ".trim());
console.log(" js string methods in     depth  ".replace(/\s/g, ""));
console.log(" js string methods in     depth  ".length);
console.log(" js string methods in     depth  ".charAt(26));
console.log(" js string methods in     depth  ".substring(26));
console.log("JS String Methods in depth.".startsWith("JS"));
console.log("JS String Methods in depth.".endsWith("depth", 26));
console.log("JS String Methods in depth.".includes("Methods"));
console.log(" js string methods in     depth  ".indexOf("depth"));
console.log("JS String Methods in depth.".match(/[a-z]/g));
console.log("JS String Methods in depth.".match(/[A-Z]/g));
console.log("JS String Methods in depth.".match(/[0-9]/g));
console.log("19 JS String Methods in depth.".match(/[19]/g));
console.log("JS String Methods in depth.".repeat(3));
console.log("JS String Methods in depth.".replace("JS", "JavaScript"));
console.log("JS String Methods in depth.".slice(18));
console.log("JS String Methods in depth.".split(/\s/g));
console.log("JS String Methods in depth.".toLowerCase());
console.log("JS String Methods in depth.".toUpperCase());
